### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by dionescu** [mpictor/bazel-amd64-crosstool#1]
Thanks for putting this together! I tried running the abseil tests with this toolchain and I get an error for some of them:

/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found

Looks like it's trying to link the wrong libstdc++. I could fix it by setting LD_LIBRARY_PATH to point to the dir containing the toolchain libstdc++ but I was wondering if there's a cleaner solution here.

**Comment by mpictor** [comment]
Not that I'm aware of. Setting LD_LIBRARY_PATH in the wrapper scripts was one of the suggestions I've seen in several places.

I didn't need to set LD_LIBRARY_PATH, but I'm not entirely sure why. Perhaps just coincidence? I certainly hope that crosstool-ng wasn't linking to my system libs!

My libstdc++ _does_ include the symbol you didn't have, so it seems I wouldn't get any errors regardless of whether it was using the wrong lib:

$ `strings /usr/lib64/gcc/x86_64-pc-linux-gnu/6.4.0/libstdc++.so.6.0.22 |grep GLIBCXX_3.4.2`
```
GLIBCXX_3.4.2
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
```

I recall there being a way to cause it to use unique symbol names when compiling some library (and anything linking to it)... if I can do that for libstdc++, perhaps it's worthwhile.

**Comment by mpictor** [comment]
Oh, perhaps I misunderstood. Did you get this error from gcc or other executables in the toolchain tarball, or when running freshly-compiled code?

Either way, LD_LIBRARY_PATH is probably the best solution. If your problems are with freshly-compiled code, though, ignore my comments about the wrappers.

It's possible to inject lib search paths into binaries via [rpath](https://en.wikipedia.org/wiki/Rpath), but I doubt that's useful for unit tests. When unit tests work for many others, getting them to pass by modifying how they're built doesn't seem like a very good solution :wink:

**Comment by mpictor** [comment]
@dionescu would you mind sharing how you got this compiler working with `abseil`? I'm trying to do that but it seems I'm doing something wrong.

Did you have to copy the contents of the WORKSPACE file into abseil's WORKSPACE? I was hoping I could get bazel to read both but I'm not sure how...
